version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"

  airflow-init:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: bash -c "airflow version && airflow db init && airflow users create --username admin \
              --password admin --firstname John \
              --lastname Doe --role Admin --email peteradekolu@gmail.com"

  airflow-webserver:
    build: .
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./config:/opt/airflow/config
      - ./helpers:/opt/airflow/helpers
      - ./gck.json:/opt/airflow/gck.json

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s

  airflow-scheduler:
    build: .
    command: scheduler
    depends_on:
      airflow-webserver:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./config:/opt/airflow/config
      - ./helpers:/opt/airflow/helpers
      - ./gck.json:/opt/airflow/gck.json

volumes:
  postgres-db-volume:
